package Vista;

import Controlador.Controlador;
import DTO.CuentaDTO;
import DTO.TransaccionDTO;
import Modelo.IModelo;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebastian Moreno
 */
public class PantallaRetiro extends javax.swing.JPanel {

    private IModelo modelo;
    private Controlador control;
    private double montoTemporal;

    public PantallaRetiro(IModelo modelo, Controlador control) {
        this.modelo = modelo;
        this.control = control;
        initComponents();

        agregarListenerAInput();
        inicializarDatosCajero(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPrincipal = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        btnMiCuenta = new Vista.PanelRound();
        btnRetirarEfectivo = new javax.swing.JLabel();
        txtOtroMontoPersonalizado = new javax.swing.JLabel();
        btnMiCuenta1 = new Vista.PanelRound();
        btnCancelar = new javax.swing.JLabel();
        tablaContenedora = new javax.swing.JScrollPane();
        tablaMontosDisponibles = new javax.swing.JTable();
        panelResumen = new Vista.PanelRound();
        nombreCliente = new javax.swing.JLabel();
        txtDetalleRetiro = new javax.swing.JLabel();
        saldoFinal = new javax.swing.JLabel();
        comision = new javax.swing.JLabel();
        subHeader6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtResumenOperacion = new javax.swing.JLabel();
        subHeader8 = new javax.swing.JLabel();
        txtSaldoFinal = new javax.swing.JLabel();
        txtCantidadRetirar = new javax.swing.JLabel();
        cantidadARetirar = new javax.swing.JLabel();
        txtComision = new javax.swing.JLabel();
        saldoActual = new javax.swing.JLabel();
        inputMontoPersonalizado = new javax.swing.JTextField();
        checkbox = new java.awt.Checkbox();
        txtRetiroRapido = new javax.swing.JLabel();

        menuPrincipal.setBackground(new java.awt.Color(16, 12, 203));
        menuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Inter", 0, 60)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("¿Cuánto desea retirar?");
        menuPrincipal.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1200, -1));

        btnMiCuenta.setBackground(new java.awt.Color(54, 80, 246));
        btnMiCuenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnMiCuenta.setRoundBottomLeft(20);
        btnMiCuenta.setRoundBottomRight(20);
        btnMiCuenta.setRoundTopLeft(20);
        btnMiCuenta.setRoundTopRight(20);

        btnRetirarEfectivo.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        btnRetirarEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        btnRetirarEfectivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRetirarEfectivo.setText("Retirar Efectivo");
        btnRetirarEfectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetirarEfectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetirarEfectivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnMiCuentaLayout = new javax.swing.GroupLayout(btnMiCuenta);
        btnMiCuenta.setLayout(btnMiCuentaLayout);
        btnMiCuentaLayout.setHorizontalGroup(
            btnMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMiCuentaLayout.createSequentialGroup()
                .addComponent(btnRetirarEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnMiCuentaLayout.setVerticalGroup(
            btnMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMiCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRetirarEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuPrincipal.add(btnMiCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 650, -1, 50));

        txtOtroMontoPersonalizado.setFont(new java.awt.Font("Inter", 0, 28)); // NOI18N
        txtOtroMontoPersonalizado.setForeground(new java.awt.Color(255, 255, 255));
        txtOtroMontoPersonalizado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtOtroMontoPersonalizado.setText("Otro:");
        menuPrincipal.add(txtOtroMontoPersonalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 670, 70, -1));

        btnMiCuenta1.setBackground(new java.awt.Color(255, 102, 102));
        btnMiCuenta1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnMiCuenta1.setRoundBottomLeft(20);
        btnMiCuenta1.setRoundBottomRight(20);
        btnMiCuenta1.setRoundTopLeft(20);
        btnMiCuenta1.setRoundTopRight(20);

        btnCancelar.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnMiCuenta1Layout = new javax.swing.GroupLayout(btnMiCuenta1);
        btnMiCuenta1.setLayout(btnMiCuenta1Layout);
        btnMiCuenta1Layout.setHorizontalGroup(
            btnMiCuenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMiCuenta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        btnMiCuenta1Layout.setVerticalGroup(
            btnMiCuenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMiCuenta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPrincipal.add(btnMiCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 690, 200, 80));

        tablaMontosDisponibles.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        tablaMontosDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMontosDisponibles.setRowHeight(40);
        tablaMontosDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMontosDisponiblesMouseClicked(evt);
            }
        });
        tablaContenedora.setViewportView(tablaMontosDisponibles);

        menuPrincipal.add(tablaContenedora, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 150, 370));

        panelResumen.setBackground(new java.awt.Color(255, 255, 255));
        panelResumen.setRoundBottomLeft(20);
        panelResumen.setRoundBottomRight(20);
        panelResumen.setRoundTopLeft(20);
        panelResumen.setRoundTopRight(20);
        panelResumen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreCliente.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        nombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreCliente.setText("Juan Miguel Velázquez");
        panelResumen.add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 610, -1));

        txtDetalleRetiro.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        txtDetalleRetiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDetalleRetiro.setText("Detalle de el retiro");
        panelResumen.add(txtDetalleRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 730, -1));

        saldoFinal.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        saldoFinal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        saldoFinal.setText("$2,505.54");
        panelResumen.add(saldoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 530, -1));

        comision.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        comision.setForeground(new java.awt.Color(255, 51, 51));
        comision.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        comision.setText("-$12.00");
        panelResumen.add(comision, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 490, -1));

        subHeader6.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        subHeader6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subHeader6.setText("Saldo actual:");
        panelResumen.add(subHeader6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, -1));
        panelResumen.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 172, 750, 10));

        txtResumenOperacion.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        txtResumenOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtResumenOperacion.setText("Resumen de operación");
        panelResumen.add(txtResumenOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, -1));

        subHeader8.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        subHeader8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subHeader8.setText("Cliente:");
        panelResumen.add(subHeader8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, -1));

        txtSaldoFinal.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        txtSaldoFinal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSaldoFinal.setText("Saldo Final:");
        panelResumen.add(txtSaldoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 210, -1));

        txtCantidadRetirar.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        txtCantidadRetirar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtCantidadRetirar.setText("Cantidad a Retirar:");
        panelResumen.add(txtCantidadRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, -1));

        cantidadARetirar.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        cantidadARetirar.setForeground(new java.awt.Color(255, 51, 51));
        cantidadARetirar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cantidadARetirar.setText("-$600.00");
        panelResumen.add(cantidadARetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 490, -1));

        txtComision.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        txtComision.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtComision.setText("Comision (2%):");
        panelResumen.add(txtComision, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, -1));

        saldoActual.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        saldoActual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        saldoActual.setText("$2,505.54");
        panelResumen.add(saldoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 530, -1));

        menuPrincipal.add(panelResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 750, 390));

        inputMontoPersonalizado.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        inputMontoPersonalizado.setText("Digita un monto ($)");
        inputMontoPersonalizado.setEnabled(false);
        inputMontoPersonalizado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputMontoPersonalizadoMouseClicked(evt);
            }
        });
        inputMontoPersonalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMontoPersonalizadoActionPerformed(evt);
            }
        });
        inputMontoPersonalizado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputMontoPersonalizadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputMontoPersonalizadoKeyTyped(evt);
            }
        });
        menuPrincipal.add(inputMontoPersonalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 710, 200, -1));

        checkbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkboxMouseClicked(evt);
            }
        });
        checkbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxItemStateChanged(evt);
            }
        });
        menuPrincipal.add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 710, -1, 30));

        txtRetiroRapido.setFont(new java.awt.Font("Inter", 0, 28)); // NOI18N
        txtRetiroRapido.setForeground(new java.awt.Color(255, 255, 255));
        txtRetiroRapido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRetiroRapido.setText("Retiro rápido");
        menuPrincipal.add(txtRetiroRapido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputMontoPersonalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMontoPersonalizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMontoPersonalizadoActionPerformed

    private void tablaMontosDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMontosDisponiblesMouseClicked
        if (evt.getClickCount() > 1 && !checkbox.getState()) {
            evt.consume();
            int filaSeleccionada = tablaMontosDisponibles.rowAtPoint(evt.getPoint());

            if (filaSeleccionada >= 0) {
                Object valorCelda = tablaMontosDisponibles.getValueAt(filaSeleccionada, 0);
                double montoSeleccionado = (double) valorCelda;

                control.calcularTransaccion(montoSeleccionado);

            }
        }
    }//GEN-LAST:event_tablaMontosDisponiblesMouseClicked

    private void checkboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkboxMouseClicked

    }//GEN-LAST:event_checkboxMouseClicked

    private void checkboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxItemStateChanged
        if (checkbox.getState()) {
            inputMontoPersonalizado.setEnabled(true);
            tablaMontosDisponibles.setEnabled(false);
            tablaContenedora.setVisible(false);
            tablaMontosDisponibles.setVisible(false);
            txtRetiroRapido.setVisible(false);
        } else {
            inputMontoPersonalizado.setEnabled(false);
            tablaMontosDisponibles.setEnabled(true);
            tablaContenedora.setVisible(true);
            tablaMontosDisponibles.setVisible(true);
            txtRetiroRapido.setVisible(true);

        }
    }//GEN-LAST:event_checkboxItemStateChanged

    private void inputMontoPersonalizadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputMontoPersonalizadoMouseClicked
        inputMontoPersonalizado.setText("");
    }//GEN-LAST:event_inputMontoPersonalizadoMouseClicked

    private void btnRetirarEfectivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarEfectivoMouseClicked
        if (montoTemporal > 0) {
            // Si es válido, procede a finalizar el retiro.
            control.finalizarRetiro();
        } else {
            // Si no (sigue en 0 o es negativo), muestra un mensaje al usuario.
            JOptionPane.showMessageDialog(this, "Por favor, seleccione o ingrese un monto para continuar.", "Monto no seleccionado", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnRetirarEfectivoMouseClicked

    private void inputMontoPersonalizadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMontoPersonalizadoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMontoPersonalizadoKeyReleased

    private void inputMontoPersonalizadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMontoPersonalizadoKeyTyped

        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_inputMontoPersonalizadoKeyTyped

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        control.ingresarBanco();
    }//GEN-LAST:event_btnCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancelar;
    private Vista.PanelRound btnMiCuenta;
    private Vista.PanelRound btnMiCuenta1;
    private javax.swing.JLabel btnRetirarEfectivo;
    private javax.swing.JLabel cantidadARetirar;
    private java.awt.Checkbox checkbox;
    private javax.swing.JLabel comision;
    private javax.swing.JTextField inputMontoPersonalizado;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menuPrincipal;
    private javax.swing.JLabel nombreCliente;
    private Vista.PanelRound panelResumen;
    private javax.swing.JLabel saldoActual;
    private javax.swing.JLabel saldoFinal;
    private javax.swing.JLabel subHeader6;
    private javax.swing.JLabel subHeader8;
    private javax.swing.JScrollPane tablaContenedora;
    private javax.swing.JTable tablaMontosDisponibles;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txtCantidadRetirar;
    private javax.swing.JLabel txtComision;
    private javax.swing.JLabel txtDetalleRetiro;
    private javax.swing.JLabel txtOtroMontoPersonalizado;
    private javax.swing.JLabel txtResumenOperacion;
    private javax.swing.JLabel txtRetiroRapido;
    private javax.swing.JLabel txtSaldoFinal;
    // End of variables declaration//GEN-END:variables

    public void inicializarDatosCajero(IModelo modelo) {
        cambiarVisibilidadLabels(false);
        int dineroDisponibleCajero = modelo.getCajero().getDineroDisponible();
        double saldo = modelo.getCuenta().getSaldo();
        javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) tablaMontosDisponibles.getModel();

        tableModel.setRowCount(0);

        for (int i = 1; i <= 20; i++) {
            double monto = i * 200.00;

            if (monto >= dineroDisponibleCajero || monto >= saldo) {
                break; // Termina el bucle
            }

            tableModel.addRow(new Object[]{monto});
        }
        nombreCliente.setText(modelo.getCliente().getNombres() + " " + modelo.getCliente().getApellidoPaterno() + " "
                + modelo.getCliente().getApellidoMaterno());
        saldoActual.setText("$" + String.valueOf(modelo.getCuenta().getSaldo()));
    }

    public void mostrarDetalleRetiro() {
        cambiarVisibilidadLabels(true);
        TransaccionDTO transaccionTemporal = modelo.getTransaccion();
        this.montoTemporal = transaccionTemporal.getMonto();
        cantidadARetirar.setText("-$" + transaccionTemporal.getMonto());
        comision.setText("-$" + transaccionTemporal.getComision());
        saldoFinal.setText("$" + transaccionTemporal.getSaldoRestante());

        revalidate();
        repaint();
    }

    public void cambiarVisibilidadLabels(boolean estado) {
        // Tu código para ocultar componentes está bien
        cantidadARetirar.setVisible(estado);
        comision.setVisible(estado);
        saldoFinal.setVisible(estado);
        txtCantidadRetirar.setVisible(estado);
        txtComision.setVisible(estado);
        txtSaldoFinal.setVisible(estado);
    }

    public void agregarListenerAInput() {
        inputMontoPersonalizado.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {

            private void onTextChanged() {
                String montoEscrito = inputMontoPersonalizado.getText().trim();

                if (montoEscrito.isEmpty()) {
                    return;
                }

                try {
                    double monto = Double.parseDouble(montoEscrito);
                    control.calcularTransaccion(monto);
                } catch (NumberFormatException e) {
                    System.out.println("Entrada no válida: " + montoEscrito);
                }
            }

            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                onTextChanged();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                onTextChanged();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
            }
        });
    }

    public void mostrarErrorFondos() {
        JOptionPane.showMessageDialog(this, "Fondos insuficientes, porfavor digita una cantidad valida.", "Error: Fondos insuficientes", JOptionPane.ERROR_MESSAGE);
    }
}
