/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.Controlador;
import DTO.ClienteDTO;
import DTO.TransaccionDTO;
import Modelo.IModelo;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author moren
 */
public class PantallaRecibo extends javax.swing.JPanel {

    /**
     * Creates new form pantallaRecibo
     */
    IModelo modelo;
    Controlador control;

    public PantallaRecibo(IModelo modelo, Controlador control) {
        this.modelo = modelo;
        this.control = control;
        initComponents();
        // --- CÁLCULO PARA CENTRAR EL GIF ---
        // Dimensiones del panel principal que proporcionaste
        int panelAncho = 1200;
        int panelAlto = 800;

        // Dimensiones de tu GIF (ancho y alto)
        int gifAncho = 190;
        int gifAlto = 100;

        // Fórmula para centrar: (Tamaño del Panel - Tamaño del GIF) / 2
        int x = (panelAncho - gifAncho) / 2; // (1200 - 190) / 2 = 505
        int y = (panelAlto - gifAlto) / 2;   // (800 - 100) / 2 = 350

        // Línea corregida que posiciona el GIF en el centro exacto
        menuPrincipal.add(gifCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, gifAncho, gifAlto));

        ejecutarAnimacionDeCarga();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPrincipal = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        btnMiCuenta = new Vista.PanelRound();
        lblAceptar = new javax.swing.JLabel();
        btnMiCuenta1 = new Vista.PanelRound();
        btnCancelar = new javax.swing.JLabel();
        panelResumen = new Vista.PanelRound();
        nombreCliente = new javax.swing.JLabel();
        cantidadRetirada = new javax.swing.JLabel();
        comision = new javax.swing.JLabel();
        subHeader6 = new javax.swing.JLabel();
        txtResumenOperacion = new javax.swing.JLabel();
        subHeader8 = new javax.swing.JLabel();
        txtSaldoFinal = new javax.swing.JLabel();
        txtCantidadRetirar = new javax.swing.JLabel();
        fechaHora = new javax.swing.JLabel();
        txtComision = new javax.swing.JLabel();
        numeroCuenta = new javax.swing.JLabel();
        txtComision1 = new javax.swing.JLabel();
        saldoFinal1 = new javax.swing.JLabel();
        gifCarga = new javax.swing.JLabel();

        menuPrincipal.setBackground(new java.awt.Color(16, 12, 203));
        menuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Inter", 0, 60)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Operacion Exitosa");
        menuPrincipal.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1200, -1));

        btnMiCuenta.setBackground(new java.awt.Color(54, 80, 246));
        btnMiCuenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnMiCuenta.setRoundBottomLeft(20);
        btnMiCuenta.setRoundBottomRight(20);
        btnMiCuenta.setRoundTopLeft(20);
        btnMiCuenta.setRoundTopRight(20);
        btnMiCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMiCuentaMouseClicked(evt);
            }
        });

        lblAceptar.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        lblAceptar.setForeground(new java.awt.Color(255, 255, 255));
        lblAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAceptar.setText("Aceptar");
        lblAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnMiCuentaLayout = new javax.swing.GroupLayout(btnMiCuenta);
        btnMiCuenta.setLayout(btnMiCuentaLayout);
        btnMiCuentaLayout.setHorizontalGroup(
            btnMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMiCuentaLayout.createSequentialGroup()
                .addComponent(lblAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnMiCuentaLayout.setVerticalGroup(
            btnMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMiCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuPrincipal.add(btnMiCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 650, -1, 50));

        btnMiCuenta1.setBackground(new java.awt.Color(102, 102, 102));
        btnMiCuenta1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnMiCuenta1.setRoundBottomLeft(20);
        btnMiCuenta1.setRoundBottomRight(20);
        btnMiCuenta1.setRoundTopLeft(20);
        btnMiCuenta1.setRoundTopRight(20);

        btnCancelar.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("Imprimir Ticket");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnMiCuenta1Layout = new javax.swing.GroupLayout(btnMiCuenta1);
        btnMiCuenta1.setLayout(btnMiCuenta1Layout);
        btnMiCuenta1Layout.setHorizontalGroup(
            btnMiCuenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMiCuenta1Layout.createSequentialGroup()
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        btnMiCuenta1Layout.setVerticalGroup(
            btnMiCuenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMiCuenta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        menuPrincipal.add(btnMiCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 310, 130, 40));

        panelResumen.setBackground(new java.awt.Color(255, 255, 255));
        panelResumen.setRoundBottomLeft(20);
        panelResumen.setRoundBottomRight(20);
        panelResumen.setRoundTopLeft(20);
        panelResumen.setRoundTopRight(20);
        panelResumen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreCliente.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        nombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreCliente.setText("Juan Miguel Velázquez");
        panelResumen.add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 610, -1));

        cantidadRetirada.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        cantidadRetirada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cantidadRetirada.setText("$600.00");
        panelResumen.add(cantidadRetirada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 510, -1));

        comision.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        comision.setForeground(new java.awt.Color(255, 51, 51));
        comision.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        comision.setText("-$12.00");
        panelResumen.add(comision, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 490, -1));

        subHeader6.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        subHeader6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subHeader6.setText("Cuenta:");
        panelResumen.add(subHeader6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, -1));

        txtResumenOperacion.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        txtResumenOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtResumenOperacion.setText("Recibo de retiro");
        panelResumen.add(txtResumenOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, -1));

        subHeader8.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        subHeader8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subHeader8.setText("Cliente:");
        panelResumen.add(subHeader8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, -1));

        txtSaldoFinal.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        txtSaldoFinal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSaldoFinal.setText("Saldo Final:");
        panelResumen.add(txtSaldoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 210, -1));

        txtCantidadRetirar.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        txtCantidadRetirar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtCantidadRetirar.setText("Fecha hora: ");
        panelResumen.add(txtCantidadRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, -1));

        fechaHora.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        fechaHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fechaHora.setText("06/10/2025 9:00 PM");
        panelResumen.add(fechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 490, -1));

        txtComision.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        txtComision.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtComision.setText("Cantidad Retirada:");
        panelResumen.add(txtComision, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 210, -1));

        numeroCuenta.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        numeroCuenta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numeroCuenta.setText("**** **** **** 4152");
        panelResumen.add(numeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 600, -1));

        txtComision1.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        txtComision1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtComision1.setText("Comision (2%):");
        panelResumen.add(txtComision1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, -1));

        saldoFinal1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        saldoFinal1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        saldoFinal1.setText("$2,505.54");
        panelResumen.add(saldoFinal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 530, -1));

        gifCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading-7528_256.gif"))); // NOI18N
        panelResumen.add(gifCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 260, 270));

        menuPrincipal.add(panelResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 750, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAceptarMouseClicked

    }//GEN-LAST:event_lblAceptarMouseClicked

    private void btnMiCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiCuentaMouseClicked

    }//GEN-LAST:event_btnMiCuentaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancelar;
    private Vista.PanelRound btnMiCuenta;
    private Vista.PanelRound btnMiCuenta1;
    private javax.swing.JLabel cantidadRetirada;
    private javax.swing.JLabel comision;
    private javax.swing.JLabel fechaHora;
    private javax.swing.JLabel gifCarga;
    private javax.swing.JLabel lblAceptar;
    private javax.swing.JPanel menuPrincipal;
    private javax.swing.JLabel nombreCliente;
    private javax.swing.JLabel numeroCuenta;
    private Vista.PanelRound panelResumen;
    private javax.swing.JLabel saldoFinal1;
    private javax.swing.JLabel subHeader6;
    private javax.swing.JLabel subHeader8;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txtCantidadRetirar;
    private javax.swing.JLabel txtComision;
    private javax.swing.JLabel txtComision1;
    private javax.swing.JLabel txtResumenOperacion;
    private javax.swing.JLabel txtSaldoFinal;
    // End of variables declaration//GEN-END:variables

    public void ejecutarAnimacionDeCarga() {

        titulo.setVisible(false);
        btnMiCuenta.setVisible(false); // Botón Aceptar
        btnMiCuenta1.setVisible(false); // Botón Imprimir Ticket

        // Ocultamos el panel completo que contiene los detalles del recibo
        panelResumen.setVisible(false);

        // Mostramos el JLabel que contiene el GIF
        gifCarga.setVisible(true);

        // --- PASO 2: Crear un Timer para la pausa de 2 segundos ---
        // Usamos javax.swing.Timer para no congelar la interfaz
        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            // Este código se ejecuta DESPUÉS de los 2 segundos

            // Ocultamos el GIF
            gifCarga.setVisible(false);

            // Volvemos a mostrar los componentes
            titulo.setVisible(true);
            btnMiCuenta.setVisible(true);
            btnMiCuenta1.setVisible(true);
            panelResumen.setVisible(true);

            // Y finalmente, cargamos los datos en los componentes ya visibles
            incializarDatosTransaccion();
        });

        // --- PASO 3: Iniciar el Timer ---
        timer.setRepeats(false); // Para que solo se ejecute una vez
        timer.start();
    }

    public void incializarDatosTransaccion() {
        TransaccionDTO transaccion = modelo.getTransaccion();
        comision.setText("-$" + transaccion.getComision());
        saldoFinal1.setText("$" + transaccion.getSaldoRestante());
        ClienteDTO cliente = transaccion.getCliente();
        nombreCliente.setText(cliente.getNombres() + " " + cliente.getApellidoPaterno() + " " + cliente.getApellidoMaterno());
        numeroCuenta.setText(transaccion.getCuenta().getNumeroTarjeta());
        LocalDateTime fecha = transaccion.getFechaHora();
        String fechaFormateda = fecha.format(DateTimeFormatter.ISO_DATE_TIME);
        fechaHora.setText(fechaFormateda);
        cantidadRetirada.setText(String.valueOf(transaccion.getMonto()));

    }
}
